// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ-buo3VQrljJAAKJ2oRKdLGq3A74hCYo',
    appId: '1:244262150078:android:6b5a9dd7d916d2f96923ef',
    messagingSenderId: '244262150078',
    projectId: 'elkbusinesshub',
    storageBucket: 'elkbusinesshub.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_o-EAyD2A0wUmcq0l1WcFITspFoFgh18',
    appId: '1:244262150078:ios:bf6d274b8af84dd46923ef',
    messagingSenderId: '244262150078',
    projectId: 'elkbusinesshub',
    storageBucket: 'elkbusinesshub.appspot.com',
    androidClientId: '244262150078-sd90m4t4orbrf1knjuopcigb01oj6v8s.apps.googleusercontent.com',
    iosClientId: '244262150078-j8q2uid1pesoj6us9dtfjdsugpg3e3tm.apps.googleusercontent.com',
    iosBundleId: 'com.infinitelab.elk',
  );

}